name: CI

on:
  pull_request:
    branches: ["main"]
    types: [synchronize, labeled, unlabeled]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}
    uses: ./.github/workflows/build.yml
    with:
      #apps: '["nubificus/esp32-ota-update", "nubificus/esp32-hello_world"]'
      apps: '[
          {
            "repo": "nubificus/esp-idf-http-camera", 
            "branch":"feat_nbfc"
          },
          {
            "repo": "nubificus/esp32-hello_world", 
            "branch":"main"
          }
      ]'
      keys: '[""]'
      #keys: '["ESP32_KEY1","ESP32_KEY2"]'
      targets: '["esp32s2"]'
      builder_image: 'harbor.nbfc.io/nubificus/esp-idf:x86_64-slim'
      upload: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-upload') }}
    secrets: inherit

